local_backend: true
backend:
  name: git-gateway
  branch: master
media_folder: content/site_images
collections:
  - label: Site content
    name: content
    media_folder: ./site_images
    public_folder: site_images
    editor:
      preview: false
    files:
      - label: Header images
        name: header_images
        file: content/images.md
        fields:
          - label: Cursos
            name: cursos
            widget: image
          - label: Online
            name: online
            widget: image
          - label: Conócenos
            name: conocenos
            widget: image
          - label: Contáctenos
            name: contactenos
            widget: image
      - label: Homepage
        name: homepage
        file: content/homepage.md
        fields:
          - label: Slides
            name: slides
            widget: list
            fields:
              - label: Slide
                name: slide
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Heading
                    name: heading
                  - label: Subheading
                    name: subheading
                  - label: Button
                    name: button
                    widget: object
                    fields:
                      - label: Text
                        name: text
                      - label: Link to...
                        name: link
                        widget: select
                        options:
                          - { label: Courses page, value: 1 }
                          - { label: About page, value: 2 }
                          - { label: Information page, value: 3 }
                          - { label: Contact page, value: 4 }
      - label: Cursos
        name: cursos
        file: content/courses.md
        fields:
          - label: Body
            name: body
            widget: markdown
            buttons:
              [
                "bold",
                "italic",
                "heading-one",
                "heading-two",
                "bulleted-list",
                "link",
              ]
            editor_components: []
            modes: ["rich_text"]
      - label: Online
        name: online
        file: content/online.md
        fields:
          - label: Body
            name: body
            widget: markdown
            buttons:
              [
                "bold",
                "italic",
                "heading-one",
                "heading-two",
                "bulleted-list",
                "link",
              ]
            editor_components: ["image"]
            modes: ["rich_text"]
      - label: Oxford Test of English
        name: oxford_test_of_english
        file: content/oxford_test_of_english.md
        fields:
          - label: Body
            name: body
            widget: markdown
            buttons:
              [
                "bold",
                "italic",
                "heading-one",
                "heading-two",
                "bulleted-list",
                "link",
              ]
            editor_components: []
            modes: ["rich_text"]
      - label: Cambridge
        name: cambridge
        file: content/cambridge.md
        fields:
          - label: Body
            name: body
            widget: markdown
            buttons:
              [
                "bold",
                "italic",
                "heading-one",
                "heading-two",
                "bulleted-list",
                "link",
              ]
            editor_components: []
            modes: ["rich_text"]
      - label: Conócenos
        name: conocenos
        file: content/conocenos.md
        fields:
          - label: Body
            name: body
            widget: markdown
            buttons:
              [
                "bold",
                "italic",
                "heading-one",
                "heading-two",
                "bulleted-list",
                "link",
              ]
            editor_components: []
            modes: ["rich_text"]
  - label: Contact
    name: contact
    editor:
      preview: false
    files:
      - label: Phone and Email
        name: phone_and_email
        file: contact/phone_and_email.md
        fields:
          - label: Phone number
            name: phone_number
          - label: Email address
            name: email_address
      - label: Social media
        name: social_media
        file: contact/social_media.md
        fields:
          - label: Facebook username
            name: facebook
          - label: Instagram username
            name: instagram
          - label: Twitter username
            name: twitter
